language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

install: pip install -r requirements.txt

before_script:
    - cp .env.example .env

script: 
    - pylint create.py
    - shellcheck create_repo.sh
